# Generated by Django 4.2.16 on 2024-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_coin_original_price_coin_price_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='coin',
            name='original_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change',
            field=models.FloatField(default=0),
        ),
    ]
