# Generated by Django 4.2.16 on 2024-11-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_coin_state_alter_coin_original_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('original_price', models.FloatField(default=0)),
                ('price_change', models.FloatField(default=0)),
                ('state', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
