# Generated by Django 4.2.16 on 2024-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_delete_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='day_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='day_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='div_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
