# Generated by Django 4.2.16 on 2024-11-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
