# Generated by Django 4.2.16 on 2024-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10),
        ),
    ]
